spring:
  application:
    name: springboot-shake
  datasource:
    #数据库相关配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mpw:0gyd8pimKmaHX3RnhZvu5iMunlSjwKo6jkeVUqfr9+lWB6d3ov7580BMJKOqNFsyk9AIhuokjtHMgPcY4CNccjUYC12dSQIPu23gKGi96/g=
    username: mpw:fRWAu/MzNYYNdoSj0ak8Bw==
    password: mpw:wSf/MfMQZwCp6cR3Y7SXYQ==
  redis:
    host: mpw:DgbxNY8U11YKkzKm0Jblhw==
    port: 49970
    timeout: 5000
    password: mpw:in7IkAPb6j33ZdEfdkA9xg==
    jedis:
      pool:
        #连接池最大连接数
        max-active: 10
        #连接池最大等待时间ms
        max-wait: 3000
        #连接池最大空闲连接
        max-idle: 4
        #连接池最小空闲连接
        min-idle: 1
server:
  #访问端口
  port: 8080
  tomcat:
    #编码格式
    uri-encoding: utf-8
  servlet:
    session:
      #session生命周期
      timeout: 30m

#MyBatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml

#MyBatis
#mybatis:
#  mapper-locations: classpath:mapper/**/*Mapper.xml
#  type-aliases-package: com.sid.xk.shake.**.entity