spring:
  application:
    name: springboot-shake
  datasource:
    #数据库相关配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mpw:wTcu/dQlteKnaOPfgMscDn2GfPCUE5d5rVhi7wOsh+fOvza4e08tFvzjC9r6ipEVx6ZZgLAjaVFGUFaHHBOd6m5FrvicRvzSyZFtXha3Cjc=
    username: mpw:XaGILU2nGxjjgo1UbbY/bw==
    password: mpw:kgNqobAtuYuvQN8NaDFu4g==
  redis:
    host: mpw:HHZdEZONLmWyG6eNqBAs3w==
    port: 49970
    timeout: 5000
    password: mpw:EVSQ6uEG7hnP6N/lAT98jw==
    jedis:
      pool:
        #连接池最大连接数
        max-active: 10
        #连接池最大等待时间ms
        max-wait: 3000
        #连接池最大空闲连接
        max-idle: 4
        #连接池最小空闲连接
        min-idle: 1
server:
  #访问端口
  port: 8080
  tomcat:
    #编码格式
    uri-encoding: utf-8
  servlet:
    session:
      #session生命周期
      timeout: 30m

#MyBatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml

#MyBatis
#mybatis:
#  mapper-locations: classpath:mapper/**/*Mapper.xml
#  type-aliases-package: com.sid.xk.shake.**.entity